name: jabris_os
description: JABRIS OS - Jarvis do Homem de Ferro
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.4.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.1
  google_generative_ai: ^0.4.3
  avatar_glow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
